### ISSUE TITLE
Dynamic Chatの日本語ヘルプ記事名を適切な翻訳にしたい

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo-learn.ja-JP#1]
This issue is for Japanese translation of ExL

![image (1)](https://github.com/AdobeDocs/marketo-learn.ja-JP/assets/63525063/71917923-3e47-4bf7-99ef-f8cc88f3612c)

現状: 
Dynamic Chatの記事名が「15 分で生きて行け」となっており、違和感を感じてクリックされない可能性が高いと考えています
プロダクトにとっては重要なshort demo tutorialになるため、日本のユーザーが安心してクリックできる文言にしたいと考えています

発生場所: 
- [製品ツアーの「その他の役に立つビデオ」欄](https://experienceleague.adobe.com/docs/marketo-learn/tutorials/dynamic-chat/product-tour.html?lang=ja)
- [Dynamic Chatチュートリアル](https://experienceleague.adobe.com/docs/marketo-learn/tutorials/dynamic-chat/dynamic-chat-overview.html?lang=ja
)
- [記事本体](https://experienceleague.adobe.com/docs/marketo-learn/tutorials/dynamic-chat/go-live-in-15-minutes.html?lang=ja)

理想: 
この記事におけるgo liveは「プロダクトが本番稼働し実用される」ことだと考えています
そのため、「15分で(Dynamic Chatを)使いはじめよう！」のような記載が適切かと考えています
参考: https://globalingualife.com/golive/

直近でDynamic Chatをアップデートしていることからも注目度が上がっていく可能性があるため、

Issue in ./help/dynamic-chat/product-tour.md

**Comment by mak-adobe** [comment]
ありがとうございます。 G11N-14332 と G11N-14333 のチケットで対応を開始しました。

**Comment by naoki-kojima25** [comment]
@mak-adobe 
こちらこそありがとうございます、チケット確認しました。

自己紹介遅れましたが、12月にJapan R&DにQEとして入社した小島です。
今後もよろしくお願いします！

**Comment by mak-adobe** [comment]
@naoki-kojima25 お待たせしました。修正が完了しました。ご協力ありがとうございました。

**Comment by naoki-kojima25** [comment]
@mak-adobe 
ご対応ありがとうございます！
一点だけ確認させてください。
「発生場所」の3つのリンクのうち2つ目の「[Dynamic Chatチュートリアル](https://experienceleague.adobe.com/docs/marketo-learn/tutorials/dynamic-chat/dynamic-chat-overview.html?lang=ja)」を確認したところ、下画像のように過去の文言が表示されています。
こちらの修正もお願いできたりしますでしょうか...？
ExLへの反映まで時間がかかっているなど、他の理由でしたら申し訳ありません🙏

<img width="1000" alt="image" src="https://github.com/AdobeDocs/marketo-learn.ja-JP/assets/63525063/72270353-e540-4dc4-853b-ff8ae29e042f">
